site_name: Wiki Gobierno Digital
site_description: Divulgacion sobre gobierno digital
site_author: DR. CHRISTIAN CRUZ

theme:
  name: material
  language: es
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest

nav:
  - Inicio: index.md
  - ¿Qué es el Gobierno Digital?: que-es.md
  - Datos Abiertos: datos-abiertos.md
  - Identidad Digital: identidad-digital.md
  - Modelo Evolutivo: modelo-evolutivo.md
  - G2C: g2c.md

repo_url: https://hanibalsmith35-cmd.github.io/gobierno-digital/
